# Generated by Django 2.2.3 on 2019-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Urls',
                'unique_together': {('normal_url', 'short_url')},
            },
        ),
    ]
