# Generated by Django 2.2.3 on 2019-07-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='normal_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='urls',
            unique_together=set(),
        ),
    ]
